# Generated by Django 4.2.11 on 2024-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_cart',
            name='bc_id',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book_cart',
            name='uc_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
